### PR TITLE
File error handling

### PR DESCRIPTION
**Pull request by Mahhheshh**

### CODE REVIEW

**Comment by LyubomirT** [comment]
Thank you for your contribution! I appreciate the support. Right now I'm going to check if things work and if I have to change anything.

**Comment by LyubomirT** [comment]
LGTM. Could you please also implement the same for `demo.py`, if possible?

**Comment by Mahhheshh** [comment]
done! let me know any other changes

**Comment by LyubomirT** [comment]
> done! let me know any other changes

Thanks a bunch! The Pull Request is ready to merge. I'll change and refactor a few things, but overall it looks great.

Once again, thank you for your awesome work and your interest in contributing to this project!

**Pull request merged**
